version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn build
  # post_build:
  #   commands:
  #     - aws s3 rm --recursive s3://${DEPLOY_BUCKET_NAME} --exclude "ads-component/*"
  #     - aws s3 sync dist s3://${DEPLOY_BUCKET_NAME} --region=ap-northeast-1
  #     - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ADSMART_DISTRIBUTION_ID} --paths '/*'